//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.25 at 09:38:07 PM CST 
//


package com.parthi.spring.ws.soap.vo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.parthi.spring.ws.soap.vo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.parthi.spring.ws.soap.vo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccountDetailRequest }
     * 
     */
    public AccountDetailRequest createAccountDetailRequest() {
        return new AccountDetailRequest();
    }

    /**
     * Create an instance of {@link AccountDetailResponse }
     * 
     */
    public AccountDetailResponse createAccountDetailResponse() {
        return new AccountDetailResponse();
    }

    /**
     * Create an instance of {@link AccountDetail }
     * 
     */
    public AccountDetail createAccountDetail() {
        return new AccountDetail();
    }

    /**
     * Create an instance of {@link DetailRequest }
     * 
     */
    public DetailRequest createDetailRequest() {
        return new DetailRequest();
    }

    /**
     * Create an instance of {@link DetailResponse }
     * 
     */
    public DetailResponse createDetailResponse() {
        return new DetailResponse();
    }

    /**
     * Create an instance of {@link BankBranchDetailsRequest }
     * 
     */
    public BankBranchDetailsRequest createBankBranchDetailsRequest() {
        return new BankBranchDetailsRequest();
    }

    /**
     * Create an instance of {@link BankBranchDetailsResponse }
     * 
     */
    public BankBranchDetailsResponse createBankBranchDetailsResponse() {
        return new BankBranchDetailsResponse();
    }

    /**
     * Create an instance of {@link BankDetail }
     * 
     */
    public BankDetail createBankDetail() {
        return new BankDetail();
    }

    /**
     * Create an instance of {@link BankDetailRequest }
     * 
     */
    public BankDetailRequest createBankDetailRequest() {
        return new BankDetailRequest();
    }

    /**
     * Create an instance of {@link BankDetailResponse }
     * 
     */
    public BankDetailResponse createBankDetailResponse() {
        return new BankDetailResponse();
    }

}
