
package com.parthi.spring.ws.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "bankServicePortType", targetNamespace = "http://service.soap.ws.spring.parthi.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankServicePortType {


    /**
     * 
     * @param bankBranchDetailsRequest
     * @return
     *     returns com.parthi.spring.ws.soap.service.BankBranchDetailsResponse
     */
    @WebMethod
    @WebResult(name = "bankBranchDetailsResponse", targetNamespace = "http://service.soap.ws.spring.parthi.com/", partName = "bankBranchDetailsResponse")
    public BankBranchDetailsResponse bankBranchDetails(
        @WebParam(name = "bankBranchDetailsRequest", targetNamespace = "http://service.soap.ws.spring.parthi.com/", partName = "bankBranchDetailsRequest")
        BankBranchDetailsRequest bankBranchDetailsRequest);

    /**
     * 
     * @param bankDetailRequest
     * @return
     *     returns com.parthi.spring.ws.soap.service.BankDetailResponse
     */
    @WebMethod
    @WebResult(name = "bankDetailResponse", targetNamespace = "http://service.soap.ws.spring.parthi.com/", partName = "bankDetailResponse")
    public BankDetailResponse bankDetail(
        @WebParam(name = "bankDetailRequest", targetNamespace = "http://service.soap.ws.spring.parthi.com/", partName = "bankDetailRequest")
        BankDetailRequest bankDetailRequest);

}
