
package com.parthi.spring.ws.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "accountServicePortType", targetNamespace = "http://service.soap.ws.spring.parthi.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountServicePortType {


    /**
     * 
     * @param accountDetailRequest
     * @return
     *     returns com.parthi.spring.ws.soap.service.AccountDetailResponse
     */
    @WebMethod
    @WebResult(name = "accountDetailResponse", targetNamespace = "http://service.soap.ws.spring.parthi.com/", partName = "accountDetailResponse")
    public AccountDetailResponse accountDetail(
        @WebParam(name = "accountDetailRequest", targetNamespace = "http://service.soap.ws.spring.parthi.com/", partName = "accountDetailRequest")
        AccountDetailRequest accountDetailRequest);

    /**
     * 
     * @param detailRequest
     * @return
     *     returns com.parthi.spring.ws.soap.service.DetailResponse
     */
    @WebMethod
    @WebResult(name = "detailResponse", targetNamespace = "http://service.soap.ws.spring.parthi.com/", partName = "detailResponse")
    public DetailResponse detail(
        @WebParam(name = "detailRequest", targetNamespace = "http://service.soap.ws.spring.parthi.com/", partName = "detailRequest")
        DetailRequest detailRequest);

}
